### ISSUE TITLE
Add mapping for menu functions directly

### ISSUE THREAD

**Issue by kacperdrobny** [molecule-man/telescope-menufacture#10]
I would like to map specific menufacture functions directly, that is I'd like to omit the menu selection screen.
```
mappings = {
    search_in_directory = { [{ 'i', 'n' }] = '<C-d>' },
},
```
ie. this mapping should put me directly into directory search window so that I don't have to select "search in directory" from the menu

Great work with the plugin, thanks :)

**Comment by molecule-man** [comment]
That's a good idea. I'll try to implement this feature tomorrow.

**Comment by molecule-man** [comment]
I've added possibility to specify direct mapping via `opts`. Please see the configuration example here https://github.com/molecule-man/telescope-menufacture#add-direct-mapping-to-invoke-menu-actions.

**Comment by kacperdrobny** [comment]
thanks, great work

**Comment by kacperdrobny** [comment]
is there a chance to allow to add those new mappings directly in telescope's setup? just like the `main_menu` option
```
require('telescope').setup {
    extensions = {
        menufacture = {
            mappings = {
                main_menu = { [{ 'i', 'n' }] = '<C-^>' },
                search_in_directory = { [{ 'i', 'n' }] = '<C-d>' },
            },
        },
    }
}
```
https://github.com/erexo/dotfiles/blob/master/init.lua#L295
I have quite a lot of telescope mappings and it'd be quite ugly to add this code everywhere separately

**Comment by molecule-man** [comment]
Good idea

did it as you suggested https://github.com/molecule-man/telescope-menufacture/pull/12/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R57

please try it out

**Comment by Jendker** [comment]
With the latest changes I am getting:
```
E5108: Error executing lua: ...pe-menufacture/lua/telescope/_extensions/menufacture.lua:144: attempt to index a nil value
stack traceback:
        ...pe-menufacture/lua/telescope/_extensions/menufacture.lua:144: in function 'attach_mappings'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:287: in function 'apply_keymap'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:569: in function 'find'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:165: in function 'v'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v'
        .../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:541: in function 'fn'
        ...pe-menufacture/lua/telescope/_extensions/menufacture.lua:213: in function <...pe-menufacture/lua/telescope/_extensions/menufacture.lua:130>
        ...pe-menufacture/lua/telescope/_extensions/menufacture.lua:228: in function <...pe-menufacture/lua/telescope/_extensions/menufacture.lua:220>
```
If I trigger `<leader>sl` with the following, pretty complex mapping:
```
vim.keymap.set('n', '<leader>sl',
  require('telescope').extensions.menufacture.add_menu_with_default_mapping(
    require('telescope.builtin').live_grep,
    vim.tbl_extend('force', require('telescope').extensions.menufacture.live_grep_menu, {
      ['toggle use_regex'] = function(opts, callback)
        local flag_key = 'additional_args'
        local flag_value = "--fixed-strings"
        require('telescope').extensions.menufacture.toggle_flag(flag_key, flag_value)(opts, callback)
        local key = 'orbik_flag_' .. flag_key .. flag_value
        if opts[key] == nil then
          require('telescope').extensions.menufacture.toggle_flag(flag_key, flag_value)(opts, callback)
          opts[key] = true
        end
      end,
      ['toggle whole words'] = require('telescope').extensions.menufacture.toggle_flag('additional_args', '-w'),
      ['toggle case sensitive'] = require('telescope').extensions.menufacture.toggle_flag('additional_args', '--case-sensitive'),
    })
  ), { desc = 'Search with [l]ive grep' }
)
```

**Comment by molecule-man** [comment]
fixed the error. But while doing it I figured out that the way you are configuring the mapping will not allow you to use those changes I introduced. I'll try to find another way.

**Comment by molecule-man** [comment]
I just pushed the fix. @Jendker please try again.

**Comment by Jendker** [comment]
I works again for me now. Thank you! :)

**Comment by molecule-man** [comment]
@Jendker 
I'm not sure if you saw it. I added the feature you requested 

> is there a chance to allow to add those new mappings directly in telescope's setup? just like the `main_menu` option
> 
> ```
> require('telescope').setup {
>     extensions = {
>         menufacture = {
>             mappings = {
>                 main_menu = { [{ 'i', 'n' }] = '<C-^>' },
>                 search_in_directory = { [{ 'i', 'n' }] = '<C-d>' },
>             },
>         },
>     }
> }
> ```
> 
> https://github.com/erexo/dotfiles/blob/master/init.lua#L295 I have quite a lot of telescope mappings and it'd be quite ugly to add this code everywhere separately

I tested it with your mappings and it worked for me

**Comment by Jendker** [comment]
@molecule-man thanks for the pointer! I think I'll stick to the menu, I prefer avoiding learning too many hotkeys so I'll stick to single main menu. This menu is what I love about menufacture. I think I was asking about something else: if it's possible to respect the picker arguments https://github.com/molecule-man/telescope-menufacture/issues/9 Or did I misinterpret anything?

**Comment by molecule-man** [comment]
> Or did I misinterpret anything?

I just meant that I implemented that feature that you have requested in your  comment https://github.com/molecule-man/telescope-menufacture/issues/10#issuecomment-1877660526 when you reopened this issue, so if you don't mind and the feature works fine for you let's close this issue.

> I think I was asking about something else: if it's possible to respect the picker arguments #9.

As of now I don't have good solution for that problem unfortunately.

**Comment by kacperdrobny** [comment]
@molecule-man I was the one who created and reopened this issue, so it's me to blame
Everything works as intended, thank you so much for your work

**Comment by molecule-man** [comment]
No worries @kacperdrobny 
I didn't mean to blame :)
