### ISSUE TITLE
Feature Request: oldfiles implementation

### ISSUE THREAD

**Issue by martenmatrix** [molecule-man/telescope-menufacture#14]
Would it be possible to implement `:Telescope oldfiles`? :)

**Comment by molecule-man** [comment]
Technically possible, but might be not very useful. This extension treats telescope picker as a blackbox: when a new menu selected then the picker is re-launched with the new options. This means that menu can affect the picker only by choosing different options. The oldfiles picker https://github.com/nvim-telescope/telescope.nvim/blob/4c96370cf93e2ba287548da12d673442d0ffecc3/lua/telescope/builtin/__internal.lua#L525-L559 exposes only handful of options:
- `include_current_session`
- `cwd_only`
- `cwd`
So those are the only options we'd be able to change in the menu picker. 
@martenmatrix If you still find it useful to have menus based on this small set of options then I gladly implement it.

**Comment by molecule-man** [comment]
@martenmatrix I've added the `oldfiles` implementation with those 3 options. Check it out if this is useful for you.

**Comment by martenmatrix** [comment]
Definitely! Thank you. <3
