### ISSUE TITLE
Using in conjunction with `grep_open_files=true`?

### ISSUE THREAD

**Issue by erwin** [molecule-man/telescope-menufacture#16]
For Telescope Live Grep, I have this key binding:

```
keymap.set("n", "<leader>fb", "<cmd>lua require('telescope.builtin').live_grep({grep_open_files=true})<CR>") -- grep in open tabs
```

Would it be possible to launch telescope-menufacture's 'live_grep' preserving that option, at least initially... Then if I hit CTRL+6 I can still get the same filtering menu? 

Sorry, not very good with Lua yet so might be a n00b question...

**Comment by molecule-man** [comment]
This should be possible, the pickers in this extension accept the same options as the original pickers. In theory you can achieve it by doing something like this:

```lua
vim.keymap.set('n', '<leader>fb', function()
  require('telescope').extensions.menufacture.live_grep {grep_open_files=true}
end)
```

I'm on a long vacation so can't verify if this is 100% true but I'm like 95% sure it should work.
