### ISSUE TITLE
Error when executing the recommended bindings

### ISSUE THREAD

**Issue by stefanwatt** [molecule-man/telescope-menufacture#4]
![image](https://user-images.githubusercontent.com/50662551/224132567-f235cc58-2314-41d6-8c6c-d53948b3da2f.png)

I just use the default config and recommended bindings and get above error when doing so.
Telescope opens after dismissing the message but doesn't display any files.

**Comment by molecule-man** [comment]
Hi @stefanwatt :wave: 

the stack traceback complains about the `lower` function. But menufacture doesn't use this function. 

does the telescope builtin `require('telescope.builtin').find_files()` work for you without an error?

**Comment by molecule-man** [comment]
Maybe telescope got some update which breaks the mapping. I'll investigate further tomorrow.

**Comment by stefanwatt** [comment]
Thanks for the quick reply!
The regular telescope find_files works without error.

**Comment by stefanwatt** [comment]
Nevermind ... I had telescope pinned.
After updating it works fine.
